// <auto-generated />
namespace Exercise.EF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addcart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addcart));
        
        string IMigrationMetadata.Id
        {
            get { return "201812132053124_Add cart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
